plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - Routers.md
  - RouterBits.md
  - RouterBitTongueAndGroove.md
  - HandPowerToolManuals.md
  - HandToolManuals.md
  - StationaryPowerToolManuals.md
  - DCManuals.md
  - DustCollection.md